// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfuugcvuccxlengnjhnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmdXVnY3Z1Y2N4bGVuZ25qaG5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNjgzMzMsImV4cCI6MjA2Mjk0NDMzM30.f22mY9PkDRDIPusLT1gOOD5S-kRbwbD_5soj8e-5Ylc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);